-- Arquivo mantido apenas como orientação para instalações antigas.
-- O schema atual é versionado em database/migrations e aplicado por:
--
--   npm run db:migrate
--
-- Não copie este arquivo para o console do Neon. Execute as migrações para
-- garantir que banco, índices e trilha de auditoria fiquem na mesma versão do
-- aplicativo.
